### ISSUE TITLE
Matching `cty.DynamicPseudoType` type constraint with targets of type `cty.NilType`

### ISSUE THREAD

**Issue by Cih2001** [hashicorp/hcl-lang#427]
Related to https://github.com/hashicorp/terraform-ls/issues/1867

In the following code snippt

```hcl
locals {
  service_accounts = [for sa in [
    "a@a.com",
  ] : "serviceAccount:${sa}"]

  // local.service_accounts is not found by terrafrom-ls
  // although defined above
  subscribers = local.service_accounts
}

provider "null" {}

resource "null_resource" "example" {}
```

terraform-ls identifies `local.service_accounts` as an unreferenced origin although it is defined in line  above it. I tracked the issue down to hcl-lang. Adding

```go
if cons.OfType == cty.DynamicPseudoType && target.Type == cty.NilType {
  matchesCons = true
}
```
to the `target.Matches()` method here after
https://github.com/hashicorp/hcl-lang/blob/5de0e8551e54364a8302013deab0f67b43139d8c/reference/target.go#L204 fixes the issue.

Based on my limited knowledge of `hcl-lang`, the `service_accounts` type is not statically known and is therefore set to `NilType`. The origin also has a dynamic pseudo type, indicating similarly that it should reference a target with an unknown type (otherwise, it would have been known statically).

I just don't understand at the moment, why is the `service_accounts` target type set to `NilType` instead of `cty.DynamicPseudoType`.

I'd like to know maintainers opinion before preparing a PR to fix this. Thanks.

**Comment by dbanck** [comment]
Hi @Cih2001,

Thanks for the bug report and your impressive research into this bug!

Our target collection logic can create multiple targets per attribute depending on the schema:
https://github.com/hashicorp/hcl-lang/blob/8d59b17219fde6ef08ecedc96cb39b80db45efd9/decoder/reference_targets.go#L305-L318

For `local` blocks, we have `AsReference` set, so each attribute is addressable as a type-less reference. Hence the `NilType` target you're seeing.

We then go on to create expression-specific targets, and this will usually create a target with a dynamic pseudo-type (for locals) and nested targets. The second target would then match the reference origin (`local.service_accounts`)

But in your example, our code for tuple expressions returns no targets:
https://github.com/hashicorp/hcl-lang/blob/8d59b17219fde6ef08ecedc96cb39b80db45efd9/decoder/expr_tuple_ref_targets.go#L15-L23

We return early because we're not able create a static list for the for expression.

I think we need to rethink our logic here and how we handle for-expressions.

**Comment by Cih2001** [comment]
Thanks for the explanation it makes more sense now, also glad you find the time I invested on this helpful.

I guess I'll leave preparing a proper fix to you then. Will be happy to find this fixed in the next version of terraform-ls, and thanks for the great work.
